import json
from datetime import UTC, datetime

from bson import ObjectId
from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, Request, UploadFile

from app.core.database import get_database
from app.core.dependencies import require_permissions
from app.schemas.common import MessageResponse
from app.schemas.documents import (
    DocumentListResponse,
    DocumentResponse,
    DocumentVersionResponse,
    FolderCreate,
    FolderResponse,
    OperationalRepositoryEntry,
    OperationalRepositoryFolder,
    OperationalRepositoryResponse,
)
from app.services.audit_service import AuditService
from app.services.storage_service import StorageService
from app.services.text_extraction import TextExtractionService

router = APIRouter(prefix="/documents", tags=["Documentos"])
storage_service = StorageService()


@router.get("/operational-repository", response_model=OperationalRepositoryResponse)
async def operational_repository(
    current_user: dict = Depends(require_permissions("documents:read")),
) -> OperationalRepositoryResponse:
    """Expose department and worker traces generated by policy workflows."""
    del current_user
    db = get_database()
    folders = []
    async for folder in db["repository_folders"].find({}).sort([("name", 1)]):
        folders.append(
            OperationalRepositoryFolder(
                id=str(folder.get("repository_key", folder["_id"])),
                name=str(folder.get("name", "Repositorio")),
                parent_id=folder.get("parent_repository_key"),
                department=folder.get("department"),
                is_synthetic=bool(folder.get("is_synthetic", False)),
            )
        )
    entries = []
    async for entry in db["repository_entries"].find({}).sort("stored_at", -1).limit(5_000):
        entries.append(
            OperationalRepositoryEntry(
                id=str(entry["_id"]),
                repository_id=str(entry.get("repository_key", "easydoc:departments")),
                filename=str(entry.get("filename", "bitacora.txt")),
                request_code=entry.get("request_code"),
                department=entry.get("department"),
                worker=entry.get("worker"),
                uploaded_by=entry.get("uploaded_by"),
                status=entry.get("status"),
                stored_at=entry.get("stored_at"),
                is_synthetic=bool(entry.get("is_synthetic", False)),
            )
        )
    return OperationalRepositoryResponse(folders=folders, entries=entries)


@router.post("/upload", response_model=DocumentResponse, status_code=201)
async def upload_document(
    request: Request,
    file: UploadFile = File(...),
    metadata: str = Form(...),  # JSON string of DocumentMetadata
    current_user: dict = Depends(require_permissions("documents:write")),
):
    """CU-11: Carga de documento con metadatos, extracción de texto y embedding"""
    try:
        meta_dict = json.loads(metadata)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid metadata JSON")

    # ── Leer el contenido UNA sola vez ──────────────────────────────────────
    content = await file.read()

    # Subir a S3 (pasa bytes directamente, sin re-leer)
    file_key = await storage_service.upload_file_bytes(
        file_content=content,
        filename=file.filename,
        content_type=file.content_type or "application/octet-stream",
        folder_path=f"user_{current_user['sub']}/",
    )

    # Extraer texto y generar embedding
    extracted_text = await TextExtractionService.extract_text(file, content)
    embedding = await TextExtractionService.generate_embedding(extracted_text)

    db = get_database()
    docs_col = db["documents"]

    doc = {
        "title": meta_dict.get("title", file.filename),
        "filename": file.filename,
        "content_type": file.content_type,
        "size_bytes": len(content),
        "description": meta_dict.get("description"),
        "tags": meta_dict.get("tags", []),
        "folder_id": meta_dict.get("folder_id"),
        "owner_id": current_user["sub"],
        "file_key": file_key,
        "extracted_text": extracted_text,
        "embedding": embedding,
        "version": 1,
        "is_active": True,
        "permissions": [],
        "created_at": datetime.now(UTC),
        "updated_at": datetime.now(UTC),
    }

    result = await docs_col.insert_one(doc)
    doc["_id"] = str(result.inserted_id)
    doc["id"] = doc["_id"]

    # Crear primer registro de versión
    versions_col = db["document_versions"]
    await versions_col.insert_one(
        {
            "document_id": doc["id"],
            "version": 1,
            "file_key": file_key,
            "size_bytes": len(content),
            "created_by": current_user["sub"],
            "created_at": datetime.now(UTC),
            "change_summary": "Initial upload",
        }
    )

    ip_address = getattr(request.state, "ip_address", None)
    await AuditService.log_action(
        user_id=current_user["sub"],
        action=AuditService.ACTIONS["DOC_UPLOAD"],
        entity_type="document",
        entity_id=doc["id"],
        ip_address=ip_address,
    )

    return DocumentResponse(**doc)


@router.get("/search", response_model=DocumentListResponse)
async def search_documents(
    query: str | None = Query(None),
    folder_id: str | None = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    current_user: dict = Depends(require_permissions("documents:read")),
):
    """CU-12: Búsqueda de documentos"""
    db = get_database()
    docs_col = db["documents"]

    # Basic filter: must be active
    filter_query = {"is_active": True}

    if folder_id:
        filter_query["folder_id"] = folder_id

    if query:
        # Full text search placeholder (will be replaced by Atlas Search in reality)
        filter_query["$or"] = [
            {"title": {"$regex": query, "$options": "i"}},
            {"description": {"$regex": query, "$options": "i"}},
            {"extracted_text": {"$regex": query, "$options": "i"}},
        ]

    skip = (page - 1) * page_size
    total = await docs_col.count_documents(filter_query)
    cursor = docs_col.find(filter_query).sort("created_at", -1).skip(skip).limit(page_size)

    docs = []
    async for doc in cursor:
        doc["id"] = str(doc["_id"])
        docs.append(DocumentResponse(**doc))

    return DocumentListResponse(documents=docs, total=total, page=page, page_size=page_size)


@router.get("/{doc_id}/versions", response_model=list[DocumentVersionResponse])
async def get_document_versions(
    doc_id: str, current_user: dict = Depends(require_permissions("documents:read"))
):
    """CU-13: Historial de versiones"""
    db = get_database()
    versions_col = db["document_versions"]

    cursor = versions_col.find({"document_id": doc_id}).sort("version", -1)
    versions = []
    async for v in cursor:
        v["id"] = str(v["_id"])
        versions.append(DocumentVersionResponse(**v))

    return versions


@router.get("/{doc_id}/preview")
async def get_document_preview(
    doc_id: str,
    request: Request,
    current_user: dict = Depends(require_permissions("documents:read")),
):
    """CU-15: URL prefirmada para descargar o ver documento"""
    db = get_database()
    docs_col = db["documents"]

    doc = await docs_col.find_one({"_id": ObjectId(doc_id), "is_active": True})
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    url = storage_service.get_presigned_url(doc["file_key"])

    ip_address = getattr(request.state, "ip_address", None)
    await AuditService.log_action(
        user_id=current_user["sub"],
        action=AuditService.ACTIONS["DOC_DOWNLOAD"],
        entity_type="document",
        entity_id=doc_id,
        ip_address=ip_address,
    )

    return {"url": url}


@router.delete("/{doc_id}", response_model=MessageResponse)
async def delete_document(
    doc_id: str,
    request: Request,
    current_user: dict = Depends(require_permissions("documents:delete")),
):
    """CU-16: Borrado lógico del documento"""
    db = get_database()
    docs_col = db["documents"]

    result = await docs_col.update_one(
        {"_id": ObjectId(doc_id)}, {"$set": {"is_active": False, "updated_at": datetime.now(UTC)}}
    )

    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Document not found")

    ip_address = getattr(request.state, "ip_address", None)
    await AuditService.log_action(
        user_id=current_user["sub"],
        action=AuditService.ACTIONS["DOC_DELETE"],
        entity_type="document",
        entity_id=doc_id,
        ip_address=ip_address,
    )

    return MessageResponse(message="Document deleted successfully", status_code=200)


@router.post("/folders", response_model=FolderResponse)
async def create_folder(
    data: FolderCreate, current_user: dict = Depends(require_permissions("documents:write"))
):
    """Crear carpeta"""
    db = get_database()
    folders_col = db["folders"]

    folder = {
        "name": data.name,
        "parent_id": data.parent_id,
        "owner_id": current_user["sub"],
        "created_at": datetime.now(UTC),
    }

    result = await folders_col.insert_one(folder)
    folder["_id"] = str(result.inserted_id)
    folder["id"] = folder["_id"]

    return FolderResponse(**folder)
